# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mateo/Desktop/m-perception

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mateo/Desktop/m-perception

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mateo/Desktop/m-perception/CMakeFiles /Users/mateo/Desktop/m-perception//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mateo/Desktop/m-perception/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dashcam_core

# Build rule for target.
dashcam_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dashcam_core
.PHONY : dashcam_core

# fast build rule for target.
dashcam_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/build
.PHONY : dashcam_core/fast

#=============================================================================
# Target rules for targets named live_pipeline

# Build rule for target.
live_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 live_pipeline
.PHONY : live_pipeline

# fast build rule for target.
live_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_pipeline.dir/build.make CMakeFiles/live_pipeline.dir/build
.PHONY : live_pipeline/fast

#=============================================================================
# Target rules for targets named live_viewer

# Build rule for target.
live_viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 live_viewer
.PHONY : live_viewer

# fast build rule for target.
live_viewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_viewer.dir/build.make CMakeFiles/live_viewer.dir/build
.PHONY : live_viewer/fast

#=============================================================================
# Target rules for targets named offline_replay

# Build rule for target.
offline_replay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 offline_replay
.PHONY : offline_replay

# fast build rule for target.
offline_replay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/offline_replay.dir/build.make CMakeFiles/offline_replay.dir/build
.PHONY : offline_replay/fast

#=============================================================================
# Target rules for targets named thread_runner_test

# Build rule for target.
thread_runner_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thread_runner_test
.PHONY : thread_runner_test

# fast build rule for target.
thread_runner_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_runner_test.dir/build.make CMakeFiles/thread_runner_test.dir/build
.PHONY : thread_runner_test/fast

#=============================================================================
# Target rules for targets named bounded_queue_test

# Build rule for target.
bounded_queue_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bounded_queue_test
.PHONY : bounded_queue_test

# fast build rule for target.
bounded_queue_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bounded_queue_test.dir/build.make CMakeFiles/bounded_queue_test.dir/build
.PHONY : bounded_queue_test/fast

apps/live_pipeline.o: apps/live_pipeline.cpp.o
.PHONY : apps/live_pipeline.o

# target to build an object file
apps/live_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_pipeline.dir/build.make CMakeFiles/live_pipeline.dir/apps/live_pipeline.cpp.o
.PHONY : apps/live_pipeline.cpp.o

apps/live_pipeline.i: apps/live_pipeline.cpp.i
.PHONY : apps/live_pipeline.i

# target to preprocess a source file
apps/live_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_pipeline.dir/build.make CMakeFiles/live_pipeline.dir/apps/live_pipeline.cpp.i
.PHONY : apps/live_pipeline.cpp.i

apps/live_pipeline.s: apps/live_pipeline.cpp.s
.PHONY : apps/live_pipeline.s

# target to generate assembly for a file
apps/live_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_pipeline.dir/build.make CMakeFiles/live_pipeline.dir/apps/live_pipeline.cpp.s
.PHONY : apps/live_pipeline.cpp.s

apps/live_viewer.o: apps/live_viewer.cpp.o
.PHONY : apps/live_viewer.o

# target to build an object file
apps/live_viewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_viewer.dir/build.make CMakeFiles/live_viewer.dir/apps/live_viewer.cpp.o
.PHONY : apps/live_viewer.cpp.o

apps/live_viewer.i: apps/live_viewer.cpp.i
.PHONY : apps/live_viewer.i

# target to preprocess a source file
apps/live_viewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_viewer.dir/build.make CMakeFiles/live_viewer.dir/apps/live_viewer.cpp.i
.PHONY : apps/live_viewer.cpp.i

apps/live_viewer.s: apps/live_viewer.cpp.s
.PHONY : apps/live_viewer.s

# target to generate assembly for a file
apps/live_viewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/live_viewer.dir/build.make CMakeFiles/live_viewer.dir/apps/live_viewer.cpp.s
.PHONY : apps/live_viewer.cpp.s

apps/offline_replay.o: apps/offline_replay.cpp.o
.PHONY : apps/offline_replay.o

# target to build an object file
apps/offline_replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/offline_replay.dir/build.make CMakeFiles/offline_replay.dir/apps/offline_replay.cpp.o
.PHONY : apps/offline_replay.cpp.o

apps/offline_replay.i: apps/offline_replay.cpp.i
.PHONY : apps/offline_replay.i

# target to preprocess a source file
apps/offline_replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/offline_replay.dir/build.make CMakeFiles/offline_replay.dir/apps/offline_replay.cpp.i
.PHONY : apps/offline_replay.cpp.i

apps/offline_replay.s: apps/offline_replay.cpp.s
.PHONY : apps/offline_replay.s

# target to generate assembly for a file
apps/offline_replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/offline_replay.dir/build.make CMakeFiles/offline_replay.dir/apps/offline_replay.cpp.s
.PHONY : apps/offline_replay.cpp.s

src/apps/ansi_dashboard.o: src/apps/ansi_dashboard.cpp.o
.PHONY : src/apps/ansi_dashboard.o

# target to build an object file
src/apps/ansi_dashboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/apps/ansi_dashboard.cpp.o
.PHONY : src/apps/ansi_dashboard.cpp.o

src/apps/ansi_dashboard.i: src/apps/ansi_dashboard.cpp.i
.PHONY : src/apps/ansi_dashboard.i

# target to preprocess a source file
src/apps/ansi_dashboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/apps/ansi_dashboard.cpp.i
.PHONY : src/apps/ansi_dashboard.cpp.i

src/apps/ansi_dashboard.s: src/apps/ansi_dashboard.cpp.s
.PHONY : src/apps/ansi_dashboard.s

# target to generate assembly for a file
src/apps/ansi_dashboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/apps/ansi_dashboard.cpp.s
.PHONY : src/apps/ansi_dashboard.cpp.s

src/apps/hud_overlay.o: src/apps/hud_overlay.cpp.o
.PHONY : src/apps/hud_overlay.o

# target to build an object file
src/apps/hud_overlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/apps/hud_overlay.cpp.o
.PHONY : src/apps/hud_overlay.cpp.o

src/apps/hud_overlay.i: src/apps/hud_overlay.cpp.i
.PHONY : src/apps/hud_overlay.i

# target to preprocess a source file
src/apps/hud_overlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/apps/hud_overlay.cpp.i
.PHONY : src/apps/hud_overlay.cpp.i

src/apps/hud_overlay.s: src/apps/hud_overlay.cpp.s
.PHONY : src/apps/hud_overlay.s

# target to generate assembly for a file
src/apps/hud_overlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/apps/hud_overlay.cpp.s
.PHONY : src/apps/hud_overlay.cpp.s

src/core/config_loader.o: src/core/config_loader.cpp.o
.PHONY : src/core/config_loader.o

# target to build an object file
src/core/config_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/core/config_loader.cpp.o
.PHONY : src/core/config_loader.cpp.o

src/core/config_loader.i: src/core/config_loader.cpp.i
.PHONY : src/core/config_loader.i

# target to preprocess a source file
src/core/config_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/core/config_loader.cpp.i
.PHONY : src/core/config_loader.cpp.i

src/core/config_loader.s: src/core/config_loader.cpp.s
.PHONY : src/core/config_loader.s

# target to generate assembly for a file
src/core/config_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/core/config_loader.cpp.s
.PHONY : src/core/config_loader.cpp.s

src/core/yolo_dnn.o: src/core/yolo_dnn.cpp.o
.PHONY : src/core/yolo_dnn.o

# target to build an object file
src/core/yolo_dnn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/core/yolo_dnn.cpp.o
.PHONY : src/core/yolo_dnn.cpp.o

src/core/yolo_dnn.i: src/core/yolo_dnn.cpp.i
.PHONY : src/core/yolo_dnn.i

# target to preprocess a source file
src/core/yolo_dnn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/core/yolo_dnn.cpp.i
.PHONY : src/core/yolo_dnn.cpp.i

src/core/yolo_dnn.s: src/core/yolo_dnn.cpp.s
.PHONY : src/core/yolo_dnn.s

# target to generate assembly for a file
src/core/yolo_dnn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/core/yolo_dnn.cpp.s
.PHONY : src/core/yolo_dnn.cpp.s

src/infra/thread_runner.o: src/infra/thread_runner.cpp.o
.PHONY : src/infra/thread_runner.o

# target to build an object file
src/infra/thread_runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/infra/thread_runner.cpp.o
.PHONY : src/infra/thread_runner.cpp.o

src/infra/thread_runner.i: src/infra/thread_runner.cpp.i
.PHONY : src/infra/thread_runner.i

# target to preprocess a source file
src/infra/thread_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/infra/thread_runner.cpp.i
.PHONY : src/infra/thread_runner.cpp.i

src/infra/thread_runner.s: src/infra/thread_runner.cpp.s
.PHONY : src/infra/thread_runner.s

# target to generate assembly for a file
src/infra/thread_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/infra/thread_runner.cpp.s
.PHONY : src/infra/thread_runner.cpp.s

src/stages/camera_stage.o: src/stages/camera_stage.cpp.o
.PHONY : src/stages/camera_stage.o

# target to build an object file
src/stages/camera_stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/camera_stage.cpp.o
.PHONY : src/stages/camera_stage.cpp.o

src/stages/camera_stage.i: src/stages/camera_stage.cpp.i
.PHONY : src/stages/camera_stage.i

# target to preprocess a source file
src/stages/camera_stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/camera_stage.cpp.i
.PHONY : src/stages/camera_stage.cpp.i

src/stages/camera_stage.s: src/stages/camera_stage.cpp.s
.PHONY : src/stages/camera_stage.s

# target to generate assembly for a file
src/stages/camera_stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/camera_stage.cpp.s
.PHONY : src/stages/camera_stage.cpp.s

src/stages/inference_stage.o: src/stages/inference_stage.cpp.o
.PHONY : src/stages/inference_stage.o

# target to build an object file
src/stages/inference_stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/inference_stage.cpp.o
.PHONY : src/stages/inference_stage.cpp.o

src/stages/inference_stage.i: src/stages/inference_stage.cpp.i
.PHONY : src/stages/inference_stage.i

# target to preprocess a source file
src/stages/inference_stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/inference_stage.cpp.i
.PHONY : src/stages/inference_stage.cpp.i

src/stages/inference_stage.s: src/stages/inference_stage.cpp.s
.PHONY : src/stages/inference_stage.s

# target to generate assembly for a file
src/stages/inference_stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/inference_stage.cpp.s
.PHONY : src/stages/inference_stage.cpp.s

src/stages/preprocess_stage.o: src/stages/preprocess_stage.cpp.o
.PHONY : src/stages/preprocess_stage.o

# target to build an object file
src/stages/preprocess_stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/preprocess_stage.cpp.o
.PHONY : src/stages/preprocess_stage.cpp.o

src/stages/preprocess_stage.i: src/stages/preprocess_stage.cpp.i
.PHONY : src/stages/preprocess_stage.i

# target to preprocess a source file
src/stages/preprocess_stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/preprocess_stage.cpp.i
.PHONY : src/stages/preprocess_stage.cpp.i

src/stages/preprocess_stage.s: src/stages/preprocess_stage.cpp.s
.PHONY : src/stages/preprocess_stage.s

# target to generate assembly for a file
src/stages/preprocess_stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/preprocess_stage.cpp.s
.PHONY : src/stages/preprocess_stage.cpp.s

src/stages/stage.o: src/stages/stage.cpp.o
.PHONY : src/stages/stage.o

# target to build an object file
src/stages/stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/stage.cpp.o
.PHONY : src/stages/stage.cpp.o

src/stages/stage.i: src/stages/stage.cpp.i
.PHONY : src/stages/stage.i

# target to preprocess a source file
src/stages/stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/stage.cpp.i
.PHONY : src/stages/stage.cpp.i

src/stages/stage.s: src/stages/stage.cpp.s
.PHONY : src/stages/stage.s

# target to generate assembly for a file
src/stages/stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/stage.cpp.s
.PHONY : src/stages/stage.cpp.s

src/stages/tracking_stage.o: src/stages/tracking_stage.cpp.o
.PHONY : src/stages/tracking_stage.o

# target to build an object file
src/stages/tracking_stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/tracking_stage.cpp.o
.PHONY : src/stages/tracking_stage.cpp.o

src/stages/tracking_stage.i: src/stages/tracking_stage.cpp.i
.PHONY : src/stages/tracking_stage.i

# target to preprocess a source file
src/stages/tracking_stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/tracking_stage.cpp.i
.PHONY : src/stages/tracking_stage.cpp.i

src/stages/tracking_stage.s: src/stages/tracking_stage.cpp.s
.PHONY : src/stages/tracking_stage.s

# target to generate assembly for a file
src/stages/tracking_stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dashcam_core.dir/build.make CMakeFiles/dashcam_core.dir/src/stages/tracking_stage.cpp.s
.PHONY : src/stages/tracking_stage.cpp.s

tests/bounded_queue_test.o: tests/bounded_queue_test.cpp.o
.PHONY : tests/bounded_queue_test.o

# target to build an object file
tests/bounded_queue_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bounded_queue_test.dir/build.make CMakeFiles/bounded_queue_test.dir/tests/bounded_queue_test.cpp.o
.PHONY : tests/bounded_queue_test.cpp.o

tests/bounded_queue_test.i: tests/bounded_queue_test.cpp.i
.PHONY : tests/bounded_queue_test.i

# target to preprocess a source file
tests/bounded_queue_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bounded_queue_test.dir/build.make CMakeFiles/bounded_queue_test.dir/tests/bounded_queue_test.cpp.i
.PHONY : tests/bounded_queue_test.cpp.i

tests/bounded_queue_test.s: tests/bounded_queue_test.cpp.s
.PHONY : tests/bounded_queue_test.s

# target to generate assembly for a file
tests/bounded_queue_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bounded_queue_test.dir/build.make CMakeFiles/bounded_queue_test.dir/tests/bounded_queue_test.cpp.s
.PHONY : tests/bounded_queue_test.cpp.s

tests/thread_runner_test.o: tests/thread_runner_test.cpp.o
.PHONY : tests/thread_runner_test.o

# target to build an object file
tests/thread_runner_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_runner_test.dir/build.make CMakeFiles/thread_runner_test.dir/tests/thread_runner_test.cpp.o
.PHONY : tests/thread_runner_test.cpp.o

tests/thread_runner_test.i: tests/thread_runner_test.cpp.i
.PHONY : tests/thread_runner_test.i

# target to preprocess a source file
tests/thread_runner_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_runner_test.dir/build.make CMakeFiles/thread_runner_test.dir/tests/thread_runner_test.cpp.i
.PHONY : tests/thread_runner_test.cpp.i

tests/thread_runner_test.s: tests/thread_runner_test.cpp.s
.PHONY : tests/thread_runner_test.s

# target to generate assembly for a file
tests/thread_runner_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thread_runner_test.dir/build.make CMakeFiles/thread_runner_test.dir/tests/thread_runner_test.cpp.s
.PHONY : tests/thread_runner_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bounded_queue_test"
	@echo "... dashcam_core"
	@echo "... live_pipeline"
	@echo "... live_viewer"
	@echo "... offline_replay"
	@echo "... thread_runner_test"
	@echo "... apps/live_pipeline.o"
	@echo "... apps/live_pipeline.i"
	@echo "... apps/live_pipeline.s"
	@echo "... apps/live_viewer.o"
	@echo "... apps/live_viewer.i"
	@echo "... apps/live_viewer.s"
	@echo "... apps/offline_replay.o"
	@echo "... apps/offline_replay.i"
	@echo "... apps/offline_replay.s"
	@echo "... src/apps/ansi_dashboard.o"
	@echo "... src/apps/ansi_dashboard.i"
	@echo "... src/apps/ansi_dashboard.s"
	@echo "... src/apps/hud_overlay.o"
	@echo "... src/apps/hud_overlay.i"
	@echo "... src/apps/hud_overlay.s"
	@echo "... src/core/config_loader.o"
	@echo "... src/core/config_loader.i"
	@echo "... src/core/config_loader.s"
	@echo "... src/core/yolo_dnn.o"
	@echo "... src/core/yolo_dnn.i"
	@echo "... src/core/yolo_dnn.s"
	@echo "... src/infra/thread_runner.o"
	@echo "... src/infra/thread_runner.i"
	@echo "... src/infra/thread_runner.s"
	@echo "... src/stages/camera_stage.o"
	@echo "... src/stages/camera_stage.i"
	@echo "... src/stages/camera_stage.s"
	@echo "... src/stages/inference_stage.o"
	@echo "... src/stages/inference_stage.i"
	@echo "... src/stages/inference_stage.s"
	@echo "... src/stages/preprocess_stage.o"
	@echo "... src/stages/preprocess_stage.i"
	@echo "... src/stages/preprocess_stage.s"
	@echo "... src/stages/stage.o"
	@echo "... src/stages/stage.i"
	@echo "... src/stages/stage.s"
	@echo "... src/stages/tracking_stage.o"
	@echo "... src/stages/tracking_stage.i"
	@echo "... src/stages/tracking_stage.s"
	@echo "... tests/bounded_queue_test.o"
	@echo "... tests/bounded_queue_test.i"
	@echo "... tests/bounded_queue_test.s"
	@echo "... tests/thread_runner_test.o"
	@echo "... tests/thread_runner_test.i"
	@echo "... tests/thread_runner_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

